var layer3=[{
          text:'1',
          children:[{
            text:'0',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          },{
            text:'1',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          },{
            text:'2',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          },{
            text:'3',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          },{
            text:'4',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          },{
            text:'5',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          },{
            text:'6',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          },{
            text:'7',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          },{
            text:'8',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          },{
            text:'9',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          }]
        },{
          text:'2',
          children:[{
            text:'0',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          },{
            text:'1',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          },{
            text:'2',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          },{
            text:'3',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          },{
            text:'4',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          },{
            text:'5',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          },{
            text:'6',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          },{
            text:'7',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          },{
            text:'8',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          },{
            text:'9',
            children:[{text:'0'},{text:'1'},{text:'2'},{text:'3'},{text:'4'},{text:'5'},{text:'6'},{text:'7'},{text:'8'},{text:'9'}]
          }]
        }
          ];
